export const practiceAreas = [
  'Accident & Injuries',
  'Administrative law',
  'Admiralty law',
  'Adoption law',
  'Agency law',
  'Alcohol law',
  'Alternative dispute resolution',
  'Animal law',
  'Antitrust law',
  'Art law',
  'Aviation law',
  'Banking law',
  'Bankruptcy law',
  'Bioethics',
  'Business law',
  'Business organizations law',
  'Canon law',
  'Civil law',
  'Communications law',
  'Computer law',
  'Competition law',
  'Construction law',
  'Consumer law',
  'Contract law',
  'Copyright law',
  'Corporate law ',
  'Criminal law',
  'Cryptography law',
  'Cyber law',
  'Drug control law',
  'Employment law',
  'Environmental law',
  'Family law',
  'Health and safety law',
  'Housing law',
  'Immigration law',
  'Intellectual property law',
  'International law',
  'Labour law',
  'Martial law',
  'Tax law',
  'Water law'
]
